sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vishalmalu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vishalmalu/docker-react yarn test
